### ISSUE TITLE
Update user with other properties than presence

### ISSUE THREAD

**Issue by stil4m** [Viascom/hipchat-api#29]
Currently, it is only possible to update the presence of a user via:

```
HipChat hipChat = ...
hipChat.usersApi().(someEmail, new UpdateUser(newPresence));
```

It would be nice to be able to update more properties as documented here:

https://www.hipchat.com/docs/apiv2/method/update_user

I'm willing to create a PR for this.

**Comment by nik-sta** [comment]
Hi @stil4m :-)

Thanks for getting in contact!

How do you mean _"It would be nice to be able to update more properties"_ because it is possible to update as well the other properties. Look in the test class UsersApiTest.java at line 61 an example starts. 

**Please notice the following note from Atlassian: "Any missing fields will be treated as deleted, so it is recommended to get the user, modify what you need, then call this resource to update"**

... or did I understand your question incorrectly? 

Thanks for your question and using hipchat-api.

Cheers, Nikola

**Comment by nik-sta** [comment]
We do in our test case something like this: 

``` java
HipChat hipChat = new HipChat(clientToken);

UpdateUser updateUser = new UpdateUser();
updateUser.setEmail("info@viascom.ch");
updateUser.setGroup_admin(false);
updateUser.setMention_name("HipChatBot");
updateUser.setName("HipChat-Bot");
updateUser.getRoles().add(UserRole.USER);
updateUser.setTimezone("CET");
updateUser.setTitle("Viascom Test Bot");

hipChat.usersApi().updateUser(testBotUserId, updateUser);
```

This should solve your problem :)

**Comment by stil4m** [comment]
Thank you for your extensive reply. 

I am such a dummy. I've only looked at the decompiled class file in my IntelliJ instance. This only includes the `presence` field. I missed the fact that it also extends the `CreateUser` class.

I'll close the issue.

**Comment by nik-sta** [comment]
Don't worry @stil4m it's a pleasure to see that our library is used by others. Write to us when ever you want! Cheers, Nikola
